language: java
language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  - jdk_switcher use oraclejdk8
services:
  - postgresql
  before_script:
    - psql -c "CREATE USER my WITH PASSWORD '1234';" -U postgres